BENCHMARK_SEQUENCES = {
    20: "HPHPPHHPHPPHPHHPPHPH",
    24: "HHPPHPPHPPHPPHPPHPPHPPHH",
    25: "PPHPPHHPPPPHHPPPPHHPPPPHH",
    36: "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP",
    48: "PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH",
    50: "PPHPPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH",
    60: "PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP",
    64: "HHHHHHHHHHHHPHPHPPHHPPHHPPHPPHHPPHHPPHPPHHPPHHPPHPHPHHHHHHHHHHHH",
    85: "HHHHPPPPHHHHHHHHHHHHPPPPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHPPHHPPHHPPHPH",
    100: "PPPHHPPHHHHPPHHHPHHPHHPHHHHPPPPPPPPHHHHHHPPHHHHHHPPPPPPPPPHPHHPHHHHHHHHHHHPPHHHPHHPHPPHPHHHPPPPPPHHH"
}

BENCHMARK_MAX_SCORES = {
    20: 9,
    24: 9,
    25: 8,
    36: 14,
    48: 23,
    50: 21,
    60: 36,
    64: 42,
    85: 53,
    100: 50
}

BENCHMARK_SELECTION = {
    "Length: 20": "HPHPPHHPHPPHPHHPPHPH",
    "Length: 24": "HHPPHPPHPPHPPHPPHPPHPPHH",
    "Length: 25": "PPHPPHHPPPPHHPPPPHHPPPPHH",
    "Length: 36": "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP",
    "Length: 48": "PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH",
    "Length: 50": "PPHPPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH",
    "Length: 60": "PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP",
    "Length: 64": "HHHHHHHHHHHHPHPHPPHHPPHHPPHPPHHPPHHPPHPPHHPPHHPPHPHPHHHHHHHHHHHH",
    "Length: 85": "HHHHPPPPHHHHHHHHHHHHPPPPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHPPHHPPHHPPHPH",
    "Length: 100": "PPPHHPPHHHHPPHHHPHHPHHPHHHHPPPPPPPPHHHHHHPPHHHHHHPPPPPPPPPHPHHPHHHHHHHHHHHPPHHHPHHPHPPHPHHHPPPPPPHHH"
}