import random

# Random name generator for leaderboard
ADJECTIVES = [
    "Acid", "Active", "Agile", "Alert", "Alive", "Amber", "Ancient", "Angry",
    "Arctic", "Ashy", "Awake", "Azure", "Bald", "Basic", "Beige", "Berry",
    "Big", "Bitter", "Black", "Bland", "Blank", "Blue", "Blunt", "Bold",
    "Bony", "Bossy", "Bouncy", "Brave", "Brief", "Bright", "Broad", "Bronze",
    "Brown", "Bulky", "Bumpy", "Burly", "Busy", "Calm", "Cheap", "Cheeky",
    "Cheery", "Chief", "Chilly", "Chunky", "Clean", "Clear", "Clever", "Cloudy",
    "Clumsy", "Cold", "Cool", "Coral", "Cosmic", "Cotton", "Crazy", "Creamy",
    "Crisp", "Curly", "Cute", "Cyan", "Daily", "Damp", "Dandy", "Dark",
    "Dear", "Deep", "Dense", "Dirty", "Dizzy", "Dope", "Drab", "Dry",
    "Dual", "Dull", "Dusty", "Eager", "Early", "Easy", "Edgy", "Elder",
    "Empty", "Epic", "Equal", "Evil", "Faint", "Fair", "Fake", "Fancy",
    "Fast", "Fat", "Feral", "Fierce", "Fine", "Firm", "Fit", "Flat",
    "Fluffy", "Foamy", "Fond", "Fresh", "Full", "Funky", "Funny", "Fuzzy",
    "Gentle", "Giant", "Giddy", "Gifted", "Glad", "Glum", "Gold", "Golden",
    "Good", "Goofy", "Grand", "Gray", "Great", "Green", "Grim", "Gross",
    "Groovy", "Grumpy", "Hairy", "Happy", "Hard", "Harsh", "Hasty", "Hazy",
    "Heavy", "Heroic", "High", "Hollow", "Holy", "Hot", "Huge", "Humid",
    "Hungry", "Hyper", "Icy", "Ideal", "Idle", "Ill", "Indigo", "Inner",
    "Iron", "Ivory", "Jade", "Jazz", "Jazzy", "Jelly", "Jolly", "Joyful",
    "Juicy", "Jumbo", "Jumpy", "Just", "Keen", "Kind", "King", "Lame",
    "Large", "Late", "Lazy", "Leafy", "Lean", "Left", "Legal", "Lemon",
    "Light", "Lilac", "Lime", "Little", "Lively", "Long", "Loose", "Loud",
    "Lovely", "Low", "Loyal", "Lucky", "Lumpy", "Lush", "Mad", "Magic",
    "Main", "Major", "Many", "Warm", "Matte", "Mean", "Meaty", "Mega",
    "Mellow", "Merry", "Messy", "Metal", "Micro", "Mild", "Milky", "Mini",
    "Minty", "Misty", "Modern", "Moist", "Moody", "Moon", "Mossy", "Muddy",
    "Mushy", "Musky", "Musty", "Mute", "Mystic", "Nasty", "Navy", "Near",
    "Neat", "Neon", "New", "Next", "Nice", "Nifty", "Nimble", "Noble",
    "Noisy", "Nova", "Numb", "Nutty", "Odd", "Oily", "Old", "Olive",
    "Open", "Orange", "Pale", "Pastel", "Peace", "Peach", "Peppy", "Perfect",
    "Perky", "Pink", "Plain", "Plastic", "Plump", "Plush", "Polar", "Polite",
    "Poor", "Posh", "Prim", "Proud", "Punky", "Pure", "Purple", "Quaint",
    "Quantum", "Quick", "Quiet", "Quirky", "Rad", "Radio", "Rainy", "Rapid",
    "Rare", "Rash", "Raw", "Ready", "Real", "Red", "Regal", "Retro",
    "Rich", "Right", "Ripe", "Rocky", "Rosy", "Rough", "Round", "Royal",
    "Rude", "Runny", "Rural", "Rusty", "Sad", "Safe", "Salty", "Sandy",
    "Sane", "Sassy", "Satin", "Saucy", "Scary", "Sharp", "Shiny", "Short",
    "Shy", "Sick", "Silent", "Silky", "Silly", "Silver", "Simple", "Skinny",
    "Sleek", "Sleepy", "Slick", "Slim", "Slimy", "Slow", "Small", "Smart",
    "Smoky", "Smooth", "Smug", "Snappy", "Snazzy", "Sneaky", "Snowy", "Soft",
    "Solar", "Solid", "Sonic", "Sore", "Sour", "Sparky", "Sparse", "Spicy",
    "Spiky", "Spry", "Square", "Stable", "Stale", "Stark", "Steel", "Steep",
    "Sticky", "Stiff", "Still", "Stocky", "Stormy", "Stout", "Strong", "Stuck",
    "Sunny", "Super", "Sure", "Sweet", "Swift", "Tall", "Tame", "Tan",
    "Tart", "Tasty", "Teal", "Teeny", "Tender", "Tense", "Tepid", "Testy",
    "Thick", "Thin", "Tidy", "Tight", "Tiny", "Tired", "Toasty", "Top",
    "Total", "Tough", "Toxic", "True", "Twin", "Ugly", "Ultra", "Unfair",
    "Unique", "Upper", "Urban", "Used", "Vague", "Vain", "Valid", "Vast",
    "Velvet", "Vivid", "Void", "Wacky", "Warm", "Wary", "Wavy", "Weak",
    "Weary", "Weird", "Wet", "White", "Whole", "Wicked", "Wide", "Wild",
    "Windy", "Wise", "Witty", "Wobbly", "Wonder", "Wooden", "Woolly", "Yellow",
    "Young", "Yummy", "Zany", "Zesty", "Zinc", "Zippy", "Zombie"
]

ANIMALS = [
    "Aardvark", "Albatross", "Alligator", "Alpaca", "Anaconda", "Angelfish", "Ant",
    "Anteater", "Antelope", "Ape", "Aphid", "Armadillo", "Asp", "Ass", "Baboon",
    "Badger", "Barracuda", "Bass", "Bat", "Bear", "Beaver", "Bedbug", "Bee",
    "Beetle", "Beluga", "Betta", "Bird", "Bison", "Blackbird", "Boa", "Boar",
    "Bobcat", "Bonobo", "Buffalo", "Bug", "Bull", "Bullfrog", "Butterfly", "Buzzard",
    "Camel", "Canary", "Capybara", "Cardinal", "Caribou", "Carp", "Cat",
    "Caterpillar", "Catfish", "Centipede", "Chameleon", "Chamois", "Cheetah",
    "Chicken", "Chihuahua", "Chimp", "Chimpanzee", "Chinchilla", "Chipmunk",
    "Cicada", "Clam", "Clownfish", "Cobra", "Cockatoo", "Cockroach", "Cod",
    "Collie", "Condor", "Constrictor", "Coral", "Cougar", "Cow", "Coyote", "Crab",
    "Crane", "Crawfish", "Crayfish", "Cricket", "Crocodile", "Crow", "Cuckoo",
    "Curlew", "Cuttlefish", "Dachshund", "Dalmatian", "Damselfly", "Deer", "Dingo",
    "Dinosaur", "Dodo", "Dog", "Dogfish", "Dolphin", "Donkey", "Dormouse", "Dove",
    "Dragon", "Dragonfly", "Drake", "Duck", "Dugong", "Eagle", "Earthworm",
    "Earwig", "Echidna", "Eel", "Egret", "Elephant", "Elk", "Emu", "Ermine",
    "Falcon", "Ferret", "Finch", "Firefly", "Fish", "Flamingo", "Flea", "Fly",
    "Flyingfish", "Fowl", "Fox", "Frog", "Gazelle", "Gecko", "Gerbil", "Gibbon",
    "Giraffe", "Gnat", "Gnu", "Goat", "Goldfish", "Goose", "Gopher", "Gorilla",
    "Grasshopper", "Greyhound", "Griffin", "Grouse", "Guinea", "Gull", "Guppy",
    "Haddock", "Halibut", "Hamster", "Hare", "Harrier", "Hawk", "Hedgehog",
    "Heron", "Herring", "Hippo", "Hippopotamus", "Hornet", "Horse", "Hound",
    "Hummingbird", "Husky", "Hydra", "Hyena", "Ibex", "Ibis", "Iguana", "Impala",
    "Insect", "Jackal", "Jaguar", "Jay", "Jellyfish", "Kangaroo", "Kestrel",
    "Kingfisher", "Kite", "Kiwi", "Koala", "Koi", "Komodo", "Krill", "Labrador",
    "Ladybug", "Lamprey", "Lark", "Leech", "Lemming", "Lemur", "Leopard", "Lion",
    "Lizard", "Llama", "Lobster", "Locust", "Loon", "Louse", "Lynx", "Macaw",
    "Mackerel", "Magpie", "Mallard", "Mammoth", "Manatee", "Mandrill", "Manta",
    "Mantis", "Marlin", "Marmoset", "Marmot", "Marsupial", "Mastiff", "Meerkat",
    "Mink", "Minnow", "Mite", "Mockingbird", "Mole", "Mollusk", "Mongoose",
    "Monitor", "Monkey", "Moose", "Mosquito", "Moth", "Mouse", "Mule", "Muskrat",
    "Mustang", "Myna", "Narwhal", "Nautilus", "Newt", "Nightingale", "Ocelot",
    "Octopus", "Okapi", "Opossum", "Orangutan", "Orca", "Osprey", "Ostrich",
    "Otter", "Owl", "Ox", "Oyster", "Panda", "Panther", "Parakeet", "Parrot",
    "Partridge", "Peacock", "Pelican", "Penguin", "Perch", "Pheasant", "Pig",
    "Pigeon", "Pike", "Piranha", "Platypus", "Pointer", "Poodle", "Porcupine",
    "Porpoise", "Possum", "Prawn", "Puffer", "Puffin", "Pug", "Puma", "Python",
    "Quail", "Rabbit", "Raccoon", "Ram", "Rat", "Rattlesnake", "Raven", "Ray",
    "Reindeer", "Retriever", "Rhino", "Rhinoceros", "Roadrunner", "Robin",
    "Rooster", "Rottweiler", "Salamander", "Salmon", "Sandpiper", "Sardine",
    "Sawfish", "Scallop", "Scorpion", "Seahorse", "Seal", "Shark", "Sheep",
    "Shepherd", "Shrew", "Shrimp", "Silkworm", "Silverfish", "Skink", "Skunk",
    "Sloth", "Slug", "Smelt", "Snail", "Snake", "Snapper", "Snipe", "Sole",
    "Sparrow", "Sphinx", "Spider", "Sponge", "Squid", "Squirrel", "Stag",
    "Starfish", "Starling", "Stingray", "Stoat", "Stork", "Sturgeon", "Swallow",
    "Swan", "Swordfish", "Tadpole", "Tapir", "Tarantula", "Tarpon", "Termite",
    "Terrier", "Tetra", "Thrush", "Tick", "Tiger", "Toad", "Tortoise", "Toucan",
    "Trout", "Tuna", "Turkey", "Turtle", "Unicorn", "Urchin", "Viper", "Vole",
    "Vulture", "Wallaby", "Walrus", "Warbler", "Warthog", "Wasp", "Weasel",
    "Weevil", "Whale", "Whippet", "Whitefish", "Wildcat", "Wildebeest", "Wolf",
    "Wolverine", "Wombat", "Woodchuck", "Woodpecker", "Worm", "Wren", "Yak",
    "Zebra"
]


def generate_random_name():
    adj = random.choice(ADJECTIVES)
    noun = random.choice(ANIMALS)

    return f"{adj} {noun}"